/* soapBasicHttpBinding_USCOREIWCFTestProxy.h
   Generated by gSOAP 2.8.34 for WCFTest.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapBasicHttpBinding_USCOREIWCFTestProxy_H
#define soapBasicHttpBinding_USCOREIWCFTestProxy_H
#include "soapH.h"

    class SOAP_CMAC BasicHttpBinding_USCOREIWCFTestProxy : public soap {
      public:
        /// Endpoint URL of service 'BasicHttpBinding_USCOREIWCFTestProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in WCFTest.h, if any
        /// Construct a proxy with new managing context
        BasicHttpBinding_USCOREIWCFTestProxy();
        /// Copy constructor
        BasicHttpBinding_USCOREIWCFTestProxy(const BasicHttpBinding_USCOREIWCFTestProxy& rhs);
        /// Construct proxy given a managing context
        BasicHttpBinding_USCOREIWCFTestProxy(const struct soap&);
        /// Constructor taking an endpoint URL
        BasicHttpBinding_USCOREIWCFTestProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIWCFTestProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIWCFTestProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIWCFTestProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~BasicHttpBinding_USCOREIWCFTestProxy();
        /// Initializer used by constructors
        virtual void BasicHttpBinding_USCOREIWCFTestProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual BasicHttpBinding_USCOREIWCFTestProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        BasicHttpBinding_USCOREIWCFTestProxy& operator=(const BasicHttpBinding_USCOREIWCFTestProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'DoWork' (returns SOAP_OK or error code)
        virtual int DoWork(_tempuri__DoWork *tempuri__DoWork, _tempuri__DoWorkResponse &tempuri__DoWorkResponse)
        { return this->DoWork(NULL, NULL, tempuri__DoWork, tempuri__DoWorkResponse); }
        virtual int DoWork(const char *soap_endpoint, const char *soap_action, _tempuri__DoWork *tempuri__DoWork, _tempuri__DoWorkResponse &tempuri__DoWorkResponse);
        /// Web service operation 'Add' (returns SOAP_OK or error code)
        virtual int Add(_tempuri__Add *tempuri__Add, _tempuri__AddResponse &tempuri__AddResponse)
        { return this->Add(NULL, NULL, tempuri__Add, tempuri__AddResponse); }
        virtual int Add(const char *soap_endpoint, const char *soap_action, _tempuri__Add *tempuri__Add, _tempuri__AddResponse &tempuri__AddResponse);
        /// Web service operation 'Sub' (returns SOAP_OK or error code)
        virtual int Sub(_tempuri__Sub *tempuri__Sub, _tempuri__SubResponse &tempuri__SubResponse)
        { return this->Sub(NULL, NULL, tempuri__Sub, tempuri__SubResponse); }
        virtual int Sub(const char *soap_endpoint, const char *soap_action, _tempuri__Sub *tempuri__Sub, _tempuri__SubResponse &tempuri__SubResponse);
    };
#endif
