//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ServerTest", Namespace="http://localhost:8089/ServerTest.wsdl")]
public partial class ServerTest : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback addOperationCompleted;
    
    private System.Threading.SendOrPostCallback subOperationCompleted;
    
    /// <remarks/>
    public ServerTest(string url) {
        this.Url = url;
    }
    
    /// <remarks/>
    public event addCompletedEventHandler addCompleted;
    
    /// <remarks/>
    public event subCompletedEventHandler subCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8089/ServerTest.wsdl", ResponseNamespace="http://localhost:8089/ServerTest.wsdl")]
    [return: System.Xml.Serialization.SoapElementAttribute("c")]
    public int add(int a, int b) {
        object[] results = this.Invoke("add", new object[] {
                    a,
                    b});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginadd(int a, int b, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("add", new object[] {
                    a,
                    b}, callback, asyncState);
    }
    
    /// <remarks/>
    public int Endadd(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void addAsync(int a, int b) {
        this.addAsync(a, b, null);
    }
    
    /// <remarks/>
    public void addAsync(int a, int b, object userState) {
        if ((this.addOperationCompleted == null)) {
            this.addOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddOperationCompleted);
        }
        this.InvokeAsync("add", new object[] {
                    a,
                    b}, this.addOperationCompleted, userState);
    }
    
    private void OnaddOperationCompleted(object arg) {
        if ((this.addCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.addCompleted(this, new addCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://localhost:8089/ServerTest.wsdl", ResponseNamespace="http://localhost:8089/ServerTest.wsdl")]
    [return: System.Xml.Serialization.SoapElementAttribute("c")]
    public int sub(int a, int b) {
        object[] results = this.Invoke("sub", new object[] {
                    a,
                    b});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsub(int a, int b, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sub", new object[] {
                    a,
                    b}, callback, asyncState);
    }
    
    /// <remarks/>
    public int Endsub(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void subAsync(int a, int b) {
        this.subAsync(a, b, null);
    }
    
    /// <remarks/>
    public void subAsync(int a, int b, object userState) {
        if ((this.subOperationCompleted == null)) {
            this.subOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubOperationCompleted);
        }
        this.InvokeAsync("sub", new object[] {
                    a,
                    b}, this.subOperationCompleted, userState);
    }
    
    private void OnsubOperationCompleted(object arg) {
        if ((this.subCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.subCompleted(this, new subCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void addCompletedEventHandler(object sender, addCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class addCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal addCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void subCompletedEventHandler(object sender, subCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class subCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal subCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}
